version: "3"

services:
  app:
    # user: "1000:1000"
    build:
      dockerfile: docker/dev.Dockerfile
      context: ../
    volumes:
      - ../:/code
    ports:
      - "5000:5000"
    # command: "tail -f docker/entrypoint.sh"