version: "3"

services:
  app:
    ports:
      - "5678:5678"
    environment: 
      - DEBUGGER=True
    command: ["sh", "-c", "python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run"]